package sharrow.inventory;
/**The inhouse class is used for the parts that are created / updated / deleted with the "in house" radio button checked**/
public class InHouse extends Part{
    private int machineId;
    /**this is the constructor for in house parts**/
    public InHouse(int id, String name, Double price, int stock, int min, int max, int machineId) {
        super(id, name, price, stock, min, max);
        this.machineId = machineId;
    }

    /**These methods get and set the machine id that is generated by the user after selecting the in house radio button**/
    public int getMachineId(){
        return machineId;
    }
    public void setMachineId(int machineId){
        this.machineId=machineId;
    }
}
